services:
  - type: web
    name: crypto-backend-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/tickers
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false # Set manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: false